apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-front
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-front
    spec:
      containers:
        - name: {{ .Values.appName }}-front
          image: nicodev28/img-front:latest
          env:
            - name: {{ .Values.envName }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: {{ .Values.configKey }}
            - name: {{ .Values.envName }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: {{ .Values.configKey }}
          resources:
            limits:
              cpu: "0.1"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
          ports:
            - containerPort: 80